[package]
name = "protocols"
version = "0.1.0"
edition = "2024"

[dependencies]
error = { version = "0.1.0", path = "../error" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
users = { version = "0.1.0", path = "../users" }
